### ISSUE TITLE
离线下载无法连接

### ISSUE THREAD

**Issue by aigooman** [xavier-niu/cloudreve-docker#48]
您好，我使用docker-compose方式部署，`docker-compose.yml`如下：
```yml
version: "3.5"

services:
  aria:
    image: p3terx/aria2-pro
    container_name: aria
    logging:
      options:
        max-size: 1m
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    environment:
      RPC_SECRET: "my-token"
    volumes:
      - /etc/aria:/config
      - /home/downloads:/downloads
    restart: unless-stopped

  cloudreve:
    image: xavierniu/cloudreve
    container_name: cloudreve
    ports:
      - 8011:5212
    volumes:
      - /home/file:/cloudreve/uploads
      - /home/downloads:/downloads
      - /etc/cloudreve/conf:/cloudreve/config
      - /etc/cloudreve/db:/cloudreve/db
      - /etc/cloudreve/avatar:/cloudreve/avatar
    # restart: unless-stopped
```
经检查两容器位于同一network，`docker network inspect cloudreve_default`输出如下：
```json
[
    {
        "Name": "cloudreve_default",
        "Id": "c938b0779ce54c42b9c2a48c3be1cdb0cdb87c6162113676e26953b7ccf31a02",
        "Created": "2021-07-15T02:43:25.730826185Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4bd88c9224119f52a66638f4b013900e9cc1c7b68f7203f6f9b6bdb9abbb7a92": {
                "Name": "aria",
                "EndpointID": "fd6838283d0ddc91491ab717549acf89a03a9d9027ab7af55f65c7530a65e43a",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "9b413324e0289bde5acc4fe1fc2bf813d8ffa33697dcd550aec3bf566b4eb8c7": {
                "Name": "cloudreve",
                "EndpointID": "6eebbfd1a6910d6a5b24639fddd8053f49e210cb9e99fc1b3b94597d2b6209ce",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "cloudreve",
            "com.docker.compose.version": "1.25.0"
        }
    }
]
```
此时aria RPC可以从外部访问，cloudreve中设置为：
![](https://z3.ax1x.com/2021/07/15/WmBQaR.png)
测试链接报错：`无法请求 RPC 服务, Post "http://127.0.0.1:6800/jsonrpc": dial tcp 127.0.0.1:6800: connect: connection refused`，求指点，万分感谢！
