### ISSUE TITLE
docker-compose启动不了

### ISSUE THREAD

**Issue by cikichen** [xavier-niu/cloudreve-docker#61]
**What happened?**
Creating network "cloudreve_cloudreve-network" with the default driver
Creating cloudreve_cloudreve_1 ... error
Creating cloudreve_aria2_1     ...

Creating cloudreve_aria2_1     ... error

ERROR: for cloudreve_aria2_1  Cannot start service aria2: cannot start a stopped process: unknown

ERROR: for cloudreve  Cannot start service cloudreve: cannot start a stopped process: unknown

ERROR: for aria2  Cannot start service aria2: cannot start a stopped process: unknown
ERROR: Encountered errors while bringing up the project.

**What do you expect it to be?**

**How to reproduce it?**
```
version: '3'

services:
    # caddy: 
    #     image: nginx:alpine
    #     ports: 
    #         - 80:80
    #         - 443:443
    #     volumes: 
    #         - /dockercnf/nginx/conf.d:/etc/nginx/conf.d
    #         - /dockercnf/nginx/ssl:/etc/nginx/ssl
    #     networks: 
    #         - cloudreve-network
    #     restart: unless-stopped

    aria2:
        image: p3terx/aria2-pro
        logging:
            options:
                max-size: 1m
        ports:
            - 6800:6800
            - 6888:6888
            - 6888:6888/udp
        environment:
            - PUID=0
            - PGID=0
            - RPC_SECRET=zqBz5JGP
        volumes:
            - /dockercnf/aria2/conf:/config
            - /home/aria2/temp:/downloads
        networks:
            - cloudreve-network
        restart: unless-stopped

    cloudreve:
        image: xavierniu/cloudreve
        environment:
            - PUID=0
            - PGID=0
        volumes:
            - /home/file:/cloudreve/uploads
            - /home/aria2/temp:/downloads
            - /dockercnf/cloudreve/config:/cloudreve/config
            - /dockercnf/cloudreve/db:/cloudreve/db
            - /dockercnf/cloudreve/avatar:/cloudreve/avatar
        networks:
            - cloudreve-network

networks:
    cloudreve-network: null
```

**Anything else?**
